"""
============================================================
Astravon Live Arena
Re-Identification Matcher

Purpose:
    Matches extracted ReID feature embeddings against
    the Global Identity Database to determine whether
    a detected person has been seen before.

Responsibilities:
    • Feature validation
    • Similarity calculations
    • Matching thresholds
    • Runtime statistics
    • Production-ready matching foundation

Author:
    House of Astravon

Version:
    1.0.0
============================================================
"""

from __future__ import annotations

import math
import threading
from datetime import datetime
from typing import Dict
from typing import Optional
from typing import Tuple

import numpy as np

from config import settings
from reid.identity_database import identity_database
from utils.logger import get_logger


# ============================================================
# Logger
# ============================================================

logger = get_logger("ReIDMatcher")


# ============================================================
# Matcher
# ============================================================

class ReIDMatcher:
    """
    Matches embeddings against the global identity database.

    This class does NOT perform feature extraction.

    Instead, it receives embeddings generated by the
    FeatureExtractor and determines whether they belong
    to an existing person or represent a completely
    new identity.
    """

    # ========================================================
    # Constructor
    # ========================================================

    def __init__(self) -> None:

        logger.info("Initializing ReID Matcher...")

        self.database = identity_database

        # ----------------------------------------------------
        # Matching Thresholds
        # ----------------------------------------------------

        self.cosine_threshold = getattr(
            settings,
            "REID_COSINE_THRESHOLD",
            0.82
        )

        self.euclidean_threshold = getattr(
            settings,
            "REID_EUCLIDEAN_THRESHOLD",
            0.85
        )

        self.minimum_confidence = getattr(
            settings,
            "REID_MIN_CONFIDENCE",
            0.75
        )

        self.embedding_dimension = getattr(
            settings,
            "REID_EMBEDDING_DIMENSION",
            512
        )

        # ----------------------------------------------------
        # Runtime Statistics
        # ----------------------------------------------------

        self.total_matches = 0

        self.successful_matches = 0

        self.failed_matches = 0

        self.new_identity_requests = 0

        self.average_similarity = 0.0

        self.highest_similarity = 0.0

        self.lowest_similarity = 1.0

        self.total_similarity = 0.0

        self.last_match = None

        self.last_similarity = 0.0

        self.last_match_timestamp = None

        self.created_at = datetime.now()

        self._lock = threading.RLock()

        logger.info(
            "ReID Matcher initialized successfully."
        )

    # ========================================================
    # Threshold Configuration
    # ========================================================

    def set_cosine_threshold(
        self,
        threshold: float
    ) -> None:
        """
        Update cosine similarity threshold.
        """

        if not 0 <= threshold <= 1:
            raise ValueError(
                "Threshold must be between 0 and 1."
            )

        self.cosine_threshold = threshold

        logger.info(
            f"Cosine threshold set to {threshold:.3f}"
        )

    def set_euclidean_threshold(
        self,
        threshold: float
    ) -> None:
        """
        Update Euclidean distance threshold.
        """

        if threshold <= 0:
            raise ValueError(
                "Threshold must be positive."
            )

        self.euclidean_threshold = threshold

        logger.info(
            f"Euclidean threshold set to {threshold:.3f}"
        )

    # ========================================================
    # Validation
    # ========================================================

    def validate_embedding(
        self,
        embedding: np.ndarray
    ) -> bool:
        """
        Validate an embedding before matching.
        """

        if embedding is None:
            return False

        if not isinstance(embedding, np.ndarray):
            return False

        if embedding.ndim != 1:
            return False

        if embedding.shape[0] != self.embedding_dimension:
            return False

        if np.isnan(embedding).any():
            return False

        if np.isinf(embedding).any():
            return False

        if np.linalg.norm(embedding) == 0:
            return False

        return True

    # ========================================================
    # Normalize
    # ========================================================

    def normalize(
        self,
        embedding: np.ndarray
    ) -> np.ndarray:
        """
        Normalize embedding to unit length.
        """

        norm = np.linalg.norm(embedding)

        if norm == 0:
            return embedding

        return embedding / norm

    # ========================================================
    # Cosine Similarity
    # ========================================================

    def cosine_similarity(
        self,
        embedding_a: np.ndarray,
        embedding_b: np.ndarray
    ) -> float:
        """
        Compute cosine similarity.
        """

        if (
            not self.validate_embedding(embedding_a)
            or
            not self.validate_embedding(embedding_b)
        ):
            return 0.0

        embedding_a = self.normalize(embedding_a)
        embedding_b = self.normalize(embedding_b)

        similarity = float(
            np.dot(
                embedding_a,
                embedding_b
            )
        )

        return max(
            0.0,
            min(1.0, similarity)
        )

    # ========================================================
    # Euclidean Distance
    # ========================================================

    def euclidean_distance(
        self,
        embedding_a: np.ndarray,
        embedding_b: np.ndarray
    ) -> float:
        """
        Compute Euclidean distance.
        """

        if (
            not self.validate_embedding(embedding_a)
            or
            not self.validate_embedding(embedding_b)
        ):
            return float("inf")

        distance = np.linalg.norm(
            embedding_a - embedding_b
        )

        return float(distance)

    # ========================================================
    # Distance to Similarity
    # ========================================================

    def distance_similarity(
        self,
        distance: float
    ) -> float:
        """
        Convert Euclidean distance into
        a similarity score.
        """

        if math.isinf(distance):
            return 0.0

        similarity = 1 / (1 + distance)

        return float(similarity)

    # ========================================================
    # Combined Similarity
    # ========================================================

    def combined_similarity(
        self,
        embedding_a: np.ndarray,
        embedding_b: np.ndarray
    ) -> Tuple[float, Dict]:
        """
        Calculate a combined similarity score
        using cosine similarity and Euclidean distance.
        """

        cosine = self.cosine_similarity(
            embedding_a,
            embedding_b
        )

        distance = self.euclidean_distance(
            embedding_a,
            embedding_b
        )

        euclidean_similarity = self.distance_similarity(
            distance
        )

        combined = (
            cosine * 0.75
            +
            euclidean_similarity * 0.25
        )

        metrics = {
            "cosine_similarity": round(cosine, 5),
            "euclidean_distance": round(distance, 5),
            "euclidean_similarity": round(
                euclidean_similarity,
                5
            ),
            "combined_similarity": round(
                combined,
                5
            )
        }

        return combined, metrics

    # ========================================================
    # Threshold Check
    # ========================================================

    def passes_threshold(
        self,
        similarity: float
    ) -> bool:
        """
        Check whether similarity satisfies
        the configured matching threshold.
        """

        return similarity >= self.cosine_threshold

        # ========================================================
    # Candidate Generation
    # ========================================================

    def candidate_matches(
        self,
        embedding: np.ndarray,
        limit: int = 20
    ) -> list[Dict]:
        """
        Generate candidate identities from the
        Global Identity Database.

        Candidates are sorted from highest similarity
        to lowest similarity.
        """

        candidates = []

        if not self.validate_embedding(embedding):
            return candidates

        identities = self.database.all_identities()

        for identity in identities:

            stored = identity.embedding

            if stored is None:
                continue

            similarity, metrics = self.combined_similarity(
                embedding,
                stored
            )

            candidates.append(
                {
                    "global_id": identity.global_id,
                    "camera_id": identity.camera_id,
                    "similarity": similarity,
                    "metrics": metrics,
                    "last_seen": identity.last_seen
                }
            )

        candidates.sort(
            key=lambda x: x["similarity"],
            reverse=True
        )

        return candidates[:limit]

    # ========================================================
    # Best Match
    # ========================================================

    def best_match(
        self,
        embedding: np.ndarray
    ) -> Optional[Dict]:
        """
        Returns the single best identity match.
        """

        candidates = self.candidate_matches(
            embedding,
            limit=1
        )

        if not candidates:
            return None

        return candidates[0]

    # ========================================================
    # Compute Match Confidence
    # ========================================================

    def confidence(
        self,
        similarity: float
    ) -> float:
        """
        Converts similarity into an operator-friendly
        confidence percentage.
        """

        if similarity <= self.cosine_threshold:
            return 0.0

        confidence = (
            (
                similarity -
                self.cosine_threshold
            )
            /
            (
                1.0 -
                self.cosine_threshold
            )
        ) * 100

        return round(
            min(
                100,
                max(
                    0,
                    confidence
                )
            ),
            2
        )

    # ========================================================
    # Adaptive Threshold
    # ========================================================

    def adaptive_threshold(
        self,
        candidate_count: int
    ) -> float:
        """
        Dynamically adjust the threshold based on
        database size.

        Larger databases require stricter matching.
        """

        threshold = self.cosine_threshold

        if candidate_count > 5000:

            threshold += 0.05

        elif candidate_count > 1000:

            threshold += 0.03

        elif candidate_count > 500:

            threshold += 0.02

        return min(
            threshold,
            0.95
        )

    # ========================================================
    # Match Identity
    # ========================================================

    def match(
        self,
        embedding: np.ndarray,
        camera_name: str,
        camera_id: str
    ) -> Optional[Dict]:
        """
        Attempt to match an embedding against the
        global identity database.
        """

        if not self.validate_embedding(
            embedding
        ):
            return None

        with self._lock:

            self.total_matches += 1

            identities = self.database.population()

            threshold = self.adaptive_threshold(
                identities
            )

            candidate = self.best_match(
                embedding
            )

            if candidate is None:

                self.failed_matches += 1

                return None

            similarity = candidate["similarity"]

            if similarity < threshold:

                self.failed_matches += 1

                return None

            confidence = self.confidence(
                similarity
            )

            result = {

                "global_id": candidate["global_id"],

                "camera": camera_name,

                "camera_id": camera_id,

                "matched_camera_id": candidate["camera_id"],

                # "matched_camera":
                # candidate["camera"],

                "similarity": round(
                    similarity,
                    4
                ),

                "confidence": confidence,

                "metrics": candidate["metrics"],

                "timestamp":
                datetime.now().isoformat()
            }

            self.successful_matches += 1

            self.last_match = result

            self.last_similarity = similarity

            self.last_match_timestamp = result[
                "timestamp"
            ]

            self.total_similarity += similarity

            self.average_similarity = (
                self.total_similarity
                /
                self.successful_matches
            )

            self.highest_similarity = max(
                self.highest_similarity,
                similarity
            )

            self.lowest_similarity = min(
                self.lowest_similarity,
                similarity
            )

            return result

    # ========================================================
    # Multi Camera Match
    # ========================================================

    def match_camera(
        self,
        camera_name: str,
        embedding: np.ndarray
    ) -> Optional[Dict]:
        """
        Wrapper for matching embeddings from
        different camera feeds.

        This is the primary entry point used by
        CameraManager.
        """

        return self.match(
            embedding,
            camera_name
        )

    # ========================================================
    # Top K Matches
    # ========================================================

    def top_matches(
        self,
        embedding: np.ndarray,
        k: int = 5
    ) -> list[Dict]:
        """
        Returns the top-K candidate identities.
        """

        candidates = self.candidate_matches(
            embedding,
            limit=k
        )

        for candidate in candidates:

            candidate[
                "confidence"
            ] = self.confidence(
                candidate["similarity"]
            )

        return candidates

    # ========================================================
    # Batch Matching
    # ========================================================

    def batch_match(
        self,
        embeddings: list[np.ndarray],
        camera_name: str
    ) -> list[Dict]:
        """
        Match multiple people detected within
        the same frame.
        """

        results = []

        for embedding in embeddings:

            match = self.match(
                embedding,
                camera_name
            )

            if match is not None:

                results.append(
                    match
                )

        return results
    
        # ============================================================
    # Statistics
    # ============================================================

    def statistics(self) -> dict:
        """
        Returns runtime statistics.
        """

        average_confidence = (
            self.total_confidence / self.successful_matches
            if self.successful_matches > 0
            else 0.0
        )

        return {
            "total_matches": self.total_matches,
            "successful_matches": self.successful_matches,
            "failed_matches": self.failed_matches,
            "success_rate": round(self.success_rate(), 2),
            "average_confidence": round(average_confidence, 4),
            "threshold": round(self.similarity_threshold, 4),
            "history_size": len(self.match_history),
            "adaptive_threshold": self.adaptive_threshold
        }

    # ============================================================
    # Success Rate
    # ============================================================

    def success_rate(self) -> float:
        """
        Percentage of successful matches.
        """

        if self.total_matches == 0:
            return 0.0

        return (
            self.successful_matches /
            self.total_matches
        ) * 100.0

    # ============================================================
    # Dashboard Summary
    # ============================================================

    def summary(self) -> dict:
        """
        Dashboard friendly summary.
        """

        return {
            "matches": self.total_matches,
            "successful": self.successful_matches,
            "failed": self.failed_matches,
            "success_rate": round(
                self.success_rate(),
                2
            ),
            "threshold": round(
                self.similarity_threshold,
                3
            ),
            "adaptive": self.adaptive_threshold,
            "last_match": (
                self.last_match["global_id"]
                if self.last_match
                else None
            )
        }

    # ============================================================
    # Module Information
    # ============================================================

    def info(self) -> dict:
        """
        Returns module information.
        """

        return {

            "module": "ReID Matcher",

            "status": (
                "Running"
                if self.enabled
                else "Disabled"
            ),

            "algorithm": "Cosine Similarity",

            "adaptive_threshold": (
                self.adaptive_threshold
            ),

            "threshold": round(
                self.similarity_threshold,
                3
            ),

            "history_size": len(
                self.match_history
            ),

            "total_matches": self.total_matches,

            "successful_matches": (
                self.successful_matches
            ),

            "success_rate": round(
                self.success_rate(),
                2
            )
        }

    # ============================================================
    # Match History
    # ============================================================

    def history(self) -> list:
        """
        Returns previous matches.
        """

        return list(self.match_history)

    # ============================================================
    # Reset Runtime Statistics
    # ============================================================

    def reset(self) -> None:
        """
        Clears runtime statistics.
        """

        self.match_history.clear()

        self.total_matches = 0

        self.successful_matches = 0

        self.failed_matches = 0

        self.total_confidence = 0.0

        self.last_match = None

    # ============================================================
    # Health Check
    # ============================================================

    def health(self) -> dict:
        """
        Health information.
        """

        healthy = (
            self.enabled and
            self.similarity_threshold > 0
        )

        return {

            "healthy": healthy,

            "module": "Matcher",

            "threshold": self.similarity_threshold,

            "history_size": len(
                self.match_history
            ),

            "total_matches": (
                self.total_matches
            ),

            "success_rate": round(
                self.success_rate(),
                2
            )
        }

    # ============================================================
    # Enable
    # ============================================================

    def enable(self) -> None:
        """
        Enables matcher.
        """

        self.enabled = True

    # ============================================================
    # Disable
    # ============================================================

    def disable(self) -> None:
        """
        Disables matcher.
        """

        self.enabled = False

    # ============================================================
    # Threshold Setter
    # ============================================================

    def set_threshold(
        self,
        threshold: float
    ) -> None:
        """
        Sets similarity threshold.
        """

        threshold = max(
            0.1,
            min(
                0.99,
                threshold
            )
        )

        self.similarity_threshold = threshold

    # ============================================================
    # Adaptive Threshold Toggle
    # ============================================================

    def enable_adaptive_threshold(
        self,
        enabled: bool = True
    ) -> None:
        """
        Enables or disables adaptive thresholding.
        """

        self.adaptive_threshold = enabled

    # ============================================================
    # Runtime State
    # ============================================================

    def is_running(self) -> bool:
        """
        Returns whether matcher is active.
        """

        return self.enabled

    # ============================================================
    # Last Match
    # ============================================================

    def latest(self):
        """
        Returns latest successful match.
        """

        return self.last_match

    # ============================================================
    # Utility
    # ============================================================

    @staticmethod
    def normalize_score(
        score: float
    ) -> float:
        """
        Clamps confidence.
        """

        return max(
            0.0,
            min(
                1.0,
                score
            )
        )

    @staticmethod
    def confidence_to_percentage(
        confidence: float
    ) -> float:
        """
        Converts confidence to percentage.
        """

        return round(
            confidence * 100.0,
            2
        )


# ============================================================
# Singleton
# ============================================================

matcher = ReIDMatcher()