/*
============================================================
Astravon Live Arena
Alert Panel Component

Purpose:
    Displays live alerts generated by the
    AI Engine and Emergency Response System.

Author:
    House of Astravon

Version:
    1.0.0
============================================================
*/

export default class AlertPanel {

    constructor() {

        this.container = null;

        this.alerts = [];

        this.maxAlerts = 20;

    }

    /*
    ==========================================================
    Initialize
    ==========================================================
    */

    initialize() {

        this.container = document.getElementById(
            "alertPanel"
        );

        if (!this.container) {

            console.warn(
                "[Alert Panel] Container not found."
            );

            return;

        }

        this.render();

        console.log(
            "[Alert Panel] Initialized."
        );

    }

    /*
    ==========================================================
    Render
    ==========================================================
    */

    render() {

        if (!this.container) {

            return;

        }

        let html = `

            <div class="alert-header">

                <h2>

                    🚨 Live Alerts

                </h2>

                <span class="alert-count">

                    ${this.alerts.length}

                </span>

            </div>

            <div class="alert-list">

        `;

        if (this.alerts.length === 0) {

            html += `

                <div class="alert-empty">

                    No active alerts.

                </div>

            `;

        }
        else {

            this.alerts.forEach(alert => {

                html += this.createAlert(alert);

            });

        }

        html += `

            </div>

        `;

        this.container.innerHTML = html;

    }

    /*
    ==========================================================
    Create Alert Card
    ==========================================================
    */

    createAlert(alert) {

        return `

            <div class="alert-card ${alert.level.toLowerCase()}">

                <div class="alert-icon">

                    ${this.getIcon(alert.level)}

                </div>

                <div class="alert-content">

                    <div class="alert-title">

                        ${alert.title}

                    </div>

                    <div class="alert-message">

                        ${alert.message}

                    </div>

                    <div class="alert-time">

                        ${alert.time}

                    </div>

                </div>

            </div>

        `;

    }

    /*
    ==========================================================
    Add Alert
    ==========================================================
    */

    addAlert({

        title,

        message,

        level = "INFO"

    }) {

        const alert = {

            id: Date.now(),

            title,

            message,

            level,

            time: new Date().toLocaleTimeString()

        };

        this.alerts.unshift(alert);

        if (

            this.alerts.length >

            this.maxAlerts

        ) {

            this.alerts.pop();

        }

        this.render();

        console.log(

            `[Alert] ${title}`

        );

    }

    /*
    ==========================================================
    AI Risk Alert
    ==========================================================
    */

    processRisk(risk) {

        switch (

            risk.toUpperCase()

        ) {

            case "LOW":

                break;

            case "MEDIUM":

                this.addAlert({

                    title:

                        "Moderate Crowd Density",

                    message:

                        "Crowd density is increasing.",

                    level:

                        "WARNING"

                });

                break;

            case "HIGH":

                this.addAlert({

                    title:

                        "High Crowd Risk",

                    message:

                        "Emergency personnel should prepare.",

                    level:

                        "DANGER"

                });

                break;

            case "CRITICAL":

                this.addAlert({

                    title:

                        "Critical Crowd Risk",

                    message:

                        "Immediate intervention required.",

                    level:

                        "CRITICAL"

                });

                break;

        }

    }

    /*
    ==========================================================
    Remove Alert
    ==========================================================
    */

    removeAlert(id) {

        this.alerts =

            this.alerts.filter(

                alert => alert.id !== id

            );

        this.render();

    }

    /*
    ==========================================================
    Clear Alerts
    ==========================================================
    */

    clear() {

        this.alerts = [];

        this.render();

    }

    /*
    ==========================================================
    Alert Icon
    ==========================================================
    */

    getIcon(level) {

        switch (

            level.toUpperCase()

        ) {

            case "INFO":

                return "ℹ️";

            case "SUCCESS":

                return "✅";

            case "WARNING":

                return "⚠️";

            case "DANGER":

                return "🚨";

            case "CRITICAL":

                return "🛑";

            default:

                return "🔔";

        }

    }

    /*
    ==========================================================
    Total Alerts
    ==========================================================
    */

    total() {

        return this.alerts.length;

    }

}