/*
============================================================
Astravon Live Arena
Alert Manager

Purpose:
    Handles system alerts generated by the AI engine.

Responsibilities:
    • Store alerts
    • Render alert cards
    • Filter alerts
    • Remove alerts
    • Clear alerts
    • Notify listeners

Author:
    House of Astravon

Version:
    1.0.0
============================================================
*/

class AlertManager {

    constructor() {

        this.alerts = [];

        this.listeners = [];

        this.container = null;

    }

    /*==========================================================
        Initialization
    ==========================================================*/

    initialize(containerId = "alertContainer") {

        this.container = document.getElementById(containerId);

        this.render();

    }

    /*==========================================================
        Create Alert
    ==========================================================*/

    add({

        title,

        message,

        level = "info",

        source = "AI Engine",

        timestamp = new Date()

    }) {

        const alert = {

            id: crypto.randomUUID(),

            title,

            message,

            level,

            source,

            timestamp,

            acknowledged: false

        };

        this.alerts.unshift(alert);

        this.render();

        this.notify();

        return alert;

    }

    /*==========================================================
        Remove Alert
    ==========================================================*/

    remove(id) {

        this.alerts = this.alerts.filter(

            alert => alert.id !== id

        );

        this.render();

        this.notify();

    }

    /*==========================================================
        Clear
    ==========================================================*/

    clear() {

        this.alerts = [];

        this.render();

        this.notify();

    }

    /*==========================================================
        Acknowledge
    ==========================================================*/

    acknowledge(id) {

        const alert = this.alerts.find(

            item => item.id === id

        );

        if (!alert) return;

        alert.acknowledged = true;

        this.render();

        this.notify();

    }

    /*==========================================================
        Render
    ==========================================================*/

    render() {

        if (!this.container) return;

        if (this.alerts.length === 0) {

            this.container.innerHTML = `

                <div class="empty-state">

                    <h3>

                        No Active Alerts

                    </h3>

                    <p>

                        All monitored systems are
                        operating normally.

                    </p>

                </div>

            `;

            return;

        }

        this.container.innerHTML = this.alerts

            .map(alert => this.card(alert))

            .join("");

    }

    /*==========================================================
        Alert Card
    ==========================================================*/

    card(alert) {

        return `

        <article
            class="alert-item alert-${alert.level}"
        >

            <div class="alert-icon">

                ${this.icon(alert.level)}

            </div>

            <div class="alert-content">

                <div class="alert-title">

                    ${alert.title}

                </div>

                <div class="alert-message">

                    ${alert.message}

                </div>

                <div class="alert-meta">

                    <span>

                        ${alert.source}

                    </span>

                    <span>

                        ${this.time(alert.timestamp)}

                    </span>

                </div>

            </div>

            <button
                class="btn btn-sm"
                onclick="window.AlertManager.acknowledge('${alert.id}')"
            >

                ${
                    alert.acknowledged
                    ? "Acknowledged"
                    : "Acknowledge"
                }

            </button>

        </article>

        `;

    }

    /*==========================================================
        Icons
    ==========================================================*/

    icon(level) {

        switch (level) {

            case "critical":

                return "🚨";

            case "danger":

                return "⛔";

            case "warning":

                return "⚠️";

            case "success":

                return "✅";

            default:

                return "ℹ️";

        }

    }

    /*==========================================================
        Time
    ==========================================================*/

    time(date) {

        return new Date(date)

            .toLocaleTimeString([], {

                hour: "2-digit",

                minute: "2-digit",

                second: "2-digit"

            });

    }

    /*==========================================================
        Filters
    ==========================================================*/

    getAll() {

        return [...this.alerts];

    }

    getByLevel(level) {

        return this.alerts.filter(

            alert => alert.level === level

        );

    }

    getCritical() {

        return this.getByLevel("critical");

    }

    getWarnings() {

        return this.getByLevel("warning");

    }

    getCount() {

        return this.alerts.length;

    }

    /*==========================================================
        Events
    ==========================================================*/

    subscribe(callback) {

        this.listeners.push(callback);

    }

    unsubscribe(callback) {

        this.listeners =

            this.listeners.filter(

                listener => listener !== callback

            );

    }

    notify() {

        this.listeners.forEach(

            callback => callback(this.alerts)

        );

    }

}

/*============================================================
Singleton
============================================================*/

const alertManager = new AlertManager();

/*
Allows inline acknowledgement buttons
*/

window.AlertManager = alertManager;

export default alertManager;

export {

    AlertManager

};