"""
============================================================
Astravon Live Arena
Alert Model

Purpose:
    Database model representing alerts generated
    by the AI Engine or system operators.

Author:
    House of Astravon

Version:
    1.0.0
============================================================
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    Float,
    DateTime
)

from database.base import Base


class Alert(Base):
    """
    Stores safety alerts generated by the system.
    """

    __tablename__ = "alerts"

    # ========================================================
    # Primary Key
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # ========================================================
    # Alert Information
    # ========================================================

    title = Column(
        String(150),
        nullable=False
    )

    description = Column(
        Text,
        nullable=False
    )

    category = Column(
        String(50),
        nullable=False,
        default="General"
    )

    severity = Column(
        String(20),
        nullable=False,
        default="Low"
    )

    # ========================================================
    # Arena Information
    # ========================================================

    event_name = Column(
        String(100),
        nullable=True
    )

    zone = Column(
        String(50),
        nullable=True
    )

    # ========================================================
    # AI Information
    # ========================================================

    risk_score = Column(
        Integer,
        nullable=False,
        default=0
    )

    confidence = Column(
        Float,
        nullable=False,
        default=0.0
    )

    # ========================================================
    # Alert Status
    # ========================================================

    status = Column(
        String(20),
        nullable=False,
        default="Active"
    )

    acknowledged = Column(
        Boolean,
        nullable=False,
        default=False
    )

    resolved = Column(
        Boolean,
        nullable=False,
        default=False
    )

    # ========================================================
    # Timestamps
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    acknowledged_at = Column(
        DateTime,
        nullable=True
    )

    resolved_at = Column(
        DateTime,
        nullable=True
    )

    # ========================================================
    # String Representation
    # ========================================================

    def __repr__(self):

        return (
            f"<Alert("
            f"id={self.id}, "
            f"title='{self.title}', "
            f"severity='{self.severity}', "
            f"status='{self.status}'"
            f")>"
        )