"""
============================================================
Astravon Live Arena
Report Model

Purpose:
    Database model representing generated reports.

Author:
    House of Astravon

Version:
    1.0.0
============================================================
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    JSON
)

from database.base import Base


class Report(Base):
    """
    Stores generated reports.
    """

    __tablename__ = "reports"

    # ========================================================
    # Primary Key
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # ========================================================
    # Report Information
    # ========================================================

    title = Column(
        String(150),
        nullable=False
    )

    report_type = Column(
        String(50),
        nullable=False
    )

    description = Column(
        Text,
        nullable=True
    )

    # ========================================================
    # Event Information
    # ========================================================

    event_name = Column(
        String(100),
        nullable=False
    )

    venue = Column(
        String(100),
        nullable=True
    )

    # ========================================================
    # Report Summary
    # ========================================================

    summary = Column(
        Text,
        nullable=True
    )

    recommendations = Column(
        Text,
        nullable=True
    )

    # ========================================================
    # Statistics Snapshot
    # ========================================================

    people_count = Column(
        Integer,
        default=0,
        nullable=False
    )

    highest_density = Column(
        String(20),
        default="Low",
        nullable=False
    )

    average_temperature = Column(
        Integer,
        default=25,
        nullable=False
    )

    highest_risk_score = Column(
        Integer,
        default=0,
        nullable=False
    )

    total_alerts = Column(
        Integer,
        default=0,
        nullable=False
    )

    # ========================================================
    # Export Data
    # ========================================================

    report_data = Column(
        JSON,
        nullable=True
    )

    file_name = Column(
        String(255),
        nullable=True
    )

    file_type = Column(
        String(20),
        default="JSON"
    )

    # ========================================================
    # Generated By
    # ========================================================

    generated_by = Column(
        String(100),
        default="System"
    )

    # ========================================================
    # Status
    # ========================================================

    status = Column(
        String(20),
        default="Completed"
    )

    # ========================================================
    # Timestamp
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # ========================================================
    # String Representation
    # ========================================================

    def __repr__(self):

        return (
            f"<Report("
            f"id={self.id}, "
            f"title='{self.title}', "
            f"type='{self.report_type}'"
            f")>"
        )