"""
============================================================
Astravon Live Arena
Statistics Model

Purpose:
    Database model representing a snapshot of
    crowd statistics generated by the AI Engine.

Author:
    House of Astravon

Version:
    1.0.0
============================================================
"""

from datetime import datetime

from sqlalchemy import (
    Column,
    Integer,
    Float,
    String,
    DateTime
)

from database.base import Base


class Statistics(Base):
    """
    Stores AI-generated statistics.
    """

    __tablename__ = "statistics"

    # ========================================================
    # Primary Key
    # ========================================================

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # ========================================================
    # Crowd Statistics
    # ========================================================

    people_count = Column(
        Integer,
        nullable=False,
        default=0
    )

    occupancy = Column(
        Integer,
        nullable=False,
        default=0
    )

    density = Column(
        String(20),
        nullable=False,
        default="Low"
    )

    # ========================================================
    # Environmental Statistics
    # ========================================================

    temperature = Column(
        Float,
        nullable=False,
        default=25.0
    )

    humidity = Column(
        Float,
        nullable=False,
        default=50.0
    )

    heat_index = Column(
        Float,
        nullable=False,
        default=27.0
    )

    # ========================================================
    # Risk Analysis
    # ========================================================

    risk_score = Column(
        Integer,
        nullable=False,
        default=0
    )

    risk_level = Column(
        String(20),
        nullable=False,
        default="Low"
    )

    # ========================================================
    # AI Information
    # ========================================================

    detected_objects = Column(
        Integer,
        nullable=False,
        default=0
    )

    confidence = Column(
        Float,
        nullable=False,
        default=0.0
    )

    # ========================================================
    # Performance
    # ========================================================

    processing_time = Column(
        Float,
        nullable=False,
        default=0.0
    )

    fps = Column(
        Float,
        nullable=False,
        default=0.0
    )

    # ========================================================
    # Timestamp
    # ========================================================

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    # ========================================================
    # String Representation
    # ========================================================

    def __repr__(self):

        return (
            f"<Statistics("
            f"id={self.id}, "
            f"people={self.people_count}, "
            f"risk='{self.risk_level}'"
            f")>"
        )